### ISSUE TITLE
In the primary example of this package usage in the documentation, the bound name to the Client object is the same as the package, which creates ambiguity in the example.

### ISSUE THREAD

**Issue by 357SANDIIIP** [JJMugenyi/myndmap#3] opened 2023-08-27 04:27 UTC
In the primary example of this package usage in the documentation, the bound name to the Client object is the same as the package, which creates ambiguity in the example.

_Originally posted by @PunkyMunky64 in https://github.com/amadeus4dev/amadeus-python/issues/197_

**Comment by hainesdata** [comment] 2023-08-28 05:32
Closing as this is posted in the wrong repo. If the issue is meant for this repo please reopen and provide context and references.

**Closed** 2023-08-28 05:32 UTC
Labels: documentation
